[package]
name = "wurl-auth"
version = "0.1.0"
authors = ["Espen Henriksen <dev+wurl@henriksen.is>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.4.0"
tokio-core = "0.1"

[dependencies.clap]
version = "2.31.2"
features = ["yaml"]

